CREATE TABLE chapter (id  integer, content TEXT, deleted_at datetime, extended_summary varchar(255), name varchar(255), position integer, summary varchar(255), parent_id bigint, primary key (id));
CREATE TABLE chapter_images (chapter_id bigint not null, images_id bigint not null);
CREATE TABLE chapter_tags (chapter_id bigint not null, tags_id bigint not null);
CREATE TABLE chapter_tag (id bigint not null, name varchar(255), novel_id bigint, primary key (id));
CREATE TABLE character (id  integer, content TEXT, deleted_at datetime, extended_summary varchar(255), name varchar(255), position integer, summary varchar(255), parent_id bigint, primary key (id));
CREATE TABLE character_images (character_id bigint not null, images_id bigint not null);
CREATE TABLE character_tags (character_id bigint not null, tags_id bigint not null);
CREATE TABLE character_group (id  integer, name varchar(255), position integer, novel_id bigint, primary key (id));
CREATE TABLE character_tag (id bigint not null, name varchar(255), novel_id bigint, primary key (id));
CREATE TABLE hibernate_sequence (next_val bigint);
CREATE TABLE image (id bigint not null, file_name varchar(255), primary key (id));
CREATE TABLE location (id  integer, content TEXT, deleted_at datetime, extended_summary varchar(255), name varchar(255), position integer, summary varchar(255), parent_id bigint, primary key (id));
CREATE TABLE location_images (location_id bigint not null, images_id bigint not null);
CREATE TABLE location_tags (location_id bigint not null, tags_id bigint not null);
CREATE TABLE location_group (id  integer, name varchar(255), position integer, novel_id bigint, primary key (id));
CREATE TABLE location_tag (id bigint not null, name varchar(255), novel_id bigint, primary key (id));
CREATE TABLE novel (id  integer, author varchar(255), name varchar(255), position integer, summary varchar(255), primary key (id));
CREATE TABLE part (id  integer, name varchar(255), position integer, novel_id bigint, primary key (id));
CREATE TABLE research (id  integer, content TEXT, deleted_at datetime, extended_summary varchar(255), name varchar(255), position integer, summary varchar(255), parent_id bigint, primary key (id));
CREATE TABLE research_images (research_id bigint not null, images_id bigint not null);
CREATE TABLE research_tags (research_id bigint not null, tags_id bigint not null);
CREATE TABLE research_group (id  integer, name varchar(255), position integer, novel_id bigint, primary key (id));
CREATE TABLE research_tag (id bigint not null, name varchar(255), novel_id bigint, primary key (id));
CREATE TABLE timeline_event (id bigint not null, color varchar(255), event_date datetime, name varchar(255), summary varchar(255), novel_id bigint, primary key (id));
CREATE TABLE timeline_event_chapters (timeline_event_id bigint not null, chapters_id bigint not null);
CREATE TABLE timeline_event_characters (timeline_event_id bigint not null, characters_id bigint not null);
CREATE TABLE timeline_event_locations (timeline_event_id bigint not null, locations_id bigint not null);
CREATE TABLE timeline_event_research (timeline_event_id bigint not null, research_id bigint not null);