
export enum NOVEL_ITEM_KEYS {
    NOVELS = 'NOVELS',
    PARTS = 'PARTS',
    CHAPTERS = 'CHAPTERS',
    RESEARCH_GROUPS = 'RESEARCH_GROUPS',
    RESEARCH = 'RESEARCH',
    CHARACTER_GROUPS = 'CHARACTER_GROUPS',
    CHARACTERS = 'CHARACTERS',
    LOCATION_GROUPS = 'LOCATION_GROUPS',
    LOCATIONS = 'LOCATIONS',
    TAGS = 'TAGS',
    TIMELINE = 'TIMELINE'
}


export enum DisplaySettingsKeys {
    SHOW_TITLE = 'SHOW_TITLE',
    SHOW_SUMMARY = 'SHOW_SUMMARY',
    SHOW_EXTENDED_SUMMARY = 'SHOW_EXTENDED_SUMMARY',
    SHOW_TAGS = 'SHOW_TAGS',
    SHOW_IMAGES = 'SHOW_IMAGES',
    SHOW_CONTENT = 'SHOW_CONTENT'
}