
export enum NOVEL_ITEM_KEYS {
    NOVELS = 'NOVELS',
    PARTS = 'PARTS',
    CHAPTERS = 'CHAPTERS',
    RESEARCH_GROUPS = 'RESEARCH_GROUPS',
    RESEARCH = 'RESEARCH',
    CHARACTER_GROUPS = 'CHARACTER_GROUPS',
    CHARACTERS = 'CHARACTERS',
    LOCATION_GROUPS = 'LOCATION_GROUPS',
    LOCATIONS = 'LOCATIONS',
    TAGS = 'TAGS',
    TIMELINE = 'TIMELINE'
}

export enum VIEWS {
    SUMMARY = 'summary',
    EXTENDED_SUMMARY = 'extended_summary',
    CONTENT = 'content',
    TAGS = 'tags'
}