name: Wortomat CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:

    - uses: actions/checkout@v2
    
    - run: docker build . --file Dockerfile --tag wortomat:latest

    - run: docker run -p 8085:8085 wortomat:latest

    - uses: cypress-io/github-action@v2
      with:
        browser: chrome        

