name: Wortomat CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install 

    - name: Run application
    - run: java -jar target/backend-0.0.1-SNAPSHOT.jar

    - uses: cypress-io/github-action@v2
      with:
        config-file: cypress.json
        browser: chrome  
    
    - run: mkdir staging && cp target/*.jar staging
    
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    

