name: Wortomat CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install 

    # - run: mkdir app && mv backend/target/backend-0.0.1-SNAPSHOT.jar app/wortomat.jar

    # - name: Run application
    #   run: java -jar app/wortomat.jar &

    # - uses: cypress-io/github-action@v2
    #   with:
    #     config-file: cypress.json
    #     browser: chrome  

    # - uses: actions/upload-artifact@v1
    #   if: failure()
    #   with:
    #     name: cypress-screenshots
    #     path: cypress/screenshots

    # # Test run video was always captured, so this action uses "always()" condition
    # - uses: actions/upload-artifact@v1
    #   if: always()
    #   with:
    #     name: cypress-videos
    #     path: cypress/videos

    - name: Package app
      run: cp backend/target/backend-0.0.1-SNAPSHOT.jar electron/jar/wortomat.jar && cd electron && npm install && npm run make
        
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: WortomatJAR
        path: app  

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: WortomatAPP
        path: electron/out/make/
    

